name: Deploy Nuxt 3 to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install dependencies
              run: npm install

            - name: Build the project
              run: npm run generate

            - name: Deploy to GitHub Pages
              run: npm run deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
